export const lagunaLocations = [
  'Biñan City',
  'Cabuyao City',
  'Calamba City',
  'San Pablo City',
  'Santa Rosa City',
  'Alaminos',
  'Bay',
  'Calauan',
  'Cavinti',
  'Famy',
  'Kalayaan',
  'Liliw',
  'Los Baños',
  'Luisiana',
  'Lumban',
  'Mabitac',
  'Magdalena',
  'Majayjay',
  'Nagcarlan',
  'Paete',
  'Pagsanjan',
  'Pakil',
  'Pangil',
  'Pila',
  'Rizal',
  'San Pedro',
  'Santa Cruz',
  'Santa Maria',
  'Siniloan',
  'Victoria',
];

export const experienceOptions = [
  'Harassment',
  'Discrimination',
  'Bullying',
  'Verbal Abuse',
  'Physical Assault',
  'Sexual Harassment',
  'Exclusion from Services',
  'Hate Speech',
  'Cyberbullying',
  'Family Rejection',
  'Workplace Discrimination',
  'Housing Discrimination',
  'Medical Misinformation',
  'Emotional Abuse',
  'Religious Intolerance',
  'Social Stigmatization',
  'Mental Health Neglect',
  'Police Harassment',
];
